-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgZcK/d5jLTO9bY/mB
G5I6bCkaFRV9GvHxkKbi+CNv492gCgYIKoZIzj0DAQehRANCAASyJw92kyF2MMWd
XjwKWmuVunxQla4RgQxmawzGxViJ8BzDSrOuiHONmlHMBbNc7c2swpoq5JOww5Vb
AweN/GGG
-----END PRIVATE KEY-----